- 단축키 ESC / Enter : 명령 모드/수정 모드
- RUN : Ctrl/Shift/Art + Enter 
- 셀 지우기 : X
- 코드/마크업 : Y/M


파이썬 특징
- 빌드 없이 바로 실행하는 인터프리터, 스크립트

In [4]:
# // 몫만 정수로, ** 승수
1+3, 1*3, 2-1, 3/2, 3//3, 3**3

(4, 3, 1, 1.5, 1, 27)

In [6]:
# 논리연산자
# 여러줄 주석 '''''', """""" 번거로우므로 보통 홑따옴표를 사용
'''
&& and
|| or
! not 
'''
True or False
not True

False

In [11]:
#조건문 , 보통 소괄호 없이 사용합니다,
if (5 > 3):
    print('5>3')
if 5 > 3:
    print('5>3')

5>3
5>3


In [13]:
# 반복문 기존 : 3항 연산자 반복문이 없다!!
#for (int i=0; i<3 ; i++){ }
for i in range(3): # 향상된 for문이라고 불리던 반복문
    print(i)

0
1
2


In [19]:
# for 지정된 횟수만큼 반복, while 조건을 만족할때까지 반복
import random
# 0~1 랜덤값을 생성하는데 0.1보다 작은 값을 얻겠다.
while (True):
    v = random.random()
    print(v)
    if v < 0.1:        
        break

0.5100000090719199
0.8717211941665339
0.9869418688186684
0.34604917923537293
0.8336109548362692
0.8643467328473461
0.7671823209659988
0.40575978841550886
0.9224753967848103
0.45204397318941225
0.8310187241324949
0.7419387969086881
0.3280077137943318
0.17679062615880026
0.6292585859521717
0.16482064889347092
0.4938323963256541
0.8726624434493379
0.5378136562739699
0.9548878790071598
0.0641493669244102


In [21]:
#함수
'''
기존
int add(int a, int b){
    return a+b;
}
string add(string a, string b){
    return string.format('{0}{1}', a,b);
}
'''
#셀 하나에 함수를 정의하는 것이 깨끗합니다
def add(a, b):
    return a+b

In [26]:
add(1, 3), add(1.5, 3.3), add('abc','123')

(4, 4.8, 'abc123')

In [38]:
# 클래스, 셀 하나에 정의하세요
class Lotto:
    def __init__(self, k): #생성자
        nums = [] #지역변수 (함수 실행 완료되면 사라집니다)
        self.nums = [] # 클래스변수 ( 클래스가 제거되기 전까지 남습니다)
        for i in range(k):
            self.nums.append(random.randint(1,45))
        print(self.nums)

In [40]:
#객체 생성
lotto1 = Lotto(3)
lotto2 = Lotto(5)

[9, 35, 5]
[15, 18, 1, 19, 2]


In [42]:
lotto1.nums #클래스 변수를 .으로 접근해서 사용할 수 있습니다

[9, 35, 5]

데이터 타입, 
- 딕셔너리 {키:값, 키:값...}       !엑셀의 컬럼 이름:키, 컬럼의 값들:값
- 리스트 [값, 값, 값...] 수정 가능 !언제든지 편리하게 데이터를 저장
- 튜플 (값, 값, 값) 수정불가능     !함수에서 값들을 여러개 리턴할때

In [47]:
d = {'age':30, 'city':'Seoul'}
l = [10, 'a', 'city', [1,2,3]]
t = (10, 'a', 'city', [1,2,3])
d, l, t

({'age': 30, 'city': 'Seoul'},
 [10, 'a', 'city', [1, 2, 3]],
 (10, 'a', 'city', [1, 2, 3]))

In [55]:
# 인덱스, 인덱싱
# 0을 인덱스라고 하고 반드시 정수여야 합니다,
#인덱스로 값을 꺼내는 것을 인덱싱한다고 합니다
# -1 뒤에서 첫번째 위치
# [시작 위치 : 끝 위치(전까지)]  ,  [생략:생략]
l[0], l[-1], l[1:3]

(10, [1, 2, 3], ['a', 'city'])

In [79]:
#요소들끼리 더하고 싶다 :element wise add
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [81]:
(1,2,3)+(7,4,5)

(1, 2, 3, 7, 4, 5)

List, Dict, Set 연산용으로 사용이 불가능, 메모리 사용량이 크고 느립니다

In [82]:
import numpy

In [88]:
#배열 만들기
#함수 사용시 shift+Tab 로 설명을 봅니다
numpy.arange(1, 10), numpy.arange(1, 10, 2)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [91]:
#데이터를 numpy 배열로 변환하면 연산이 됩니다
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

야후 파이낸스의 SP500 주식 데이터를 읽습니다
csv 혹은 pandas 로 읽을 수 있습니다

In [92]:
import pandas

In [96]:
stock = pandas.read_csv('^GSPC.csv')
stock.shape # 20행, 7열

(20, 7)

In [101]:
arr = np.array(stock)#배열로 변환
arr.shape

(20, 7)

In [107]:
arr[0] == arr[0, :]

array([ True,  True,  True,  True,  True,  True,  True])

In [106]:
arr[0, 0], arr[-1, -1] #첫번째 행의 첫번째 열, 마지막 행의 마지막 열

('2019-05-20', 1579314342)

In [110]:
# Open 만 가져오자 
# Date	Open	High	Low	Close	Adj Close	Volume

o = arr[:, 1]
o

array([2841.939941, 2854.02002, 2856.060059, 2836.699951, 2832.409912,
       2830.030029, 2790.25, 2786.939941, 2766.149902, 2751.530029,
       2762.639893, 2818.090088, 2828.51001, 2852.8701170000004,
       2885.830078, 2903.27002, 2882.72998, 2886.23999, 2886.820068,
       2889.75], dtype=object)

In [123]:
# b(below) 아래쪽에 셀 만들기
# open 의 최대값, 최소값, 평균을 구해보자
# 내장 함수 : import 없이 바로 사용 가능한 함수
# 통계치, 평균, 중간값, 표준편차
max(o), min(o), np.max(o), np.min(o), np.mean(o), np.median(o), np.std(o)

(2903.27002,
 2751.530029,
 2903.27002,
 2751.530029,
 2837.1390014000003,
 2839.319946,
 45.016996538592394)

In [111]:
# Close 를 가져오자
close = arr[:, 4] #도 가능하지만
close = arr[:, -3] # 이 편합니다
close

array([2840.22998, 2864.360107, 2856.27002, 2822.23999, 2826.060059,
       2802.389893, 2783.02002, 2788.860107, 2752.060059, 2744.449951,
       2803.27002, 2826.149902, 2843.48999, 2873.340088, 2886.72998,
       2885.719971, 2879.840088, 2891.639893, 2886.97998, 2889.669922],
      dtype=object)

In [124]:
# Open	High	Low	Close 4개의 컬럼만 뽑자
# [시작:끝] 
v4 = arr[:, 1:5]
v4.shape

(20, 4)

축 : axis  
2차원 데이터는 2개의 축이 있습니다. 행축, 열축

In [128]:
np.max(v4, axis=0)

array([2903.27002, 2910.610107, 2887.300049, 2891.639893], dtype=object)

In [134]:
# argmax, argmin 맥스값의 위치
np.max(o), np.argmax(o)

(2903.27002, 15)

주가가 가장 많이 상승한 날을 찾아보세요 (정답 : X 번째 행입니다)
(종가 - 시작) 이 가장 큰 날입니다

In [142]:
day = arr[:, 0]
close_v = arr[:, -3]
open_v = arr[:, 1]
gap = close_v - open_v

In [146]:
np.max(gap), np.argmax(gap), day[np.argmax(gap)]

(40.6301269999999, 10, '2019-06-04')

##### 데이터 분석
- 가격 상승하는 날 거래량이 많아질까?
- 전날 가격이 상승하면 나음날 시작가격은 더 높은 가격에서 시작할까?
- 가격 변동이 크면 거래량도 많아질까?

###### 다음 단계 : 예측
- 어제/오늘 현황 분석이 끝났는데 내일은 Open/Close 이 어떻게 될까
- 방법 : 1. 통계적(R) 2. 머신러닝

In [149]:
# 가격 상승하는 날 거래량이 많아질까?
# > 상승한 날의 거래량 / 하락한 날의 거래량
close_v = arr[:, -3]
open_v = arr[:, 1]
vol = arr[:, -1]
gap = close_v - open_v

In [163]:
# 상승한 날의 거래량의 평균
np.mean(vol[gap > 0]) , np.mean(vol[gap < 0])

(3286227000.0, 3397639434.2)

In [165]:
# 상승한 날의 거래량이 더 많냐?
np.mean(vol[gap > 0]) > np.mean(vol[gap < 0])

False

In [155]:
#조건부 검색
a = np.array([1,2,3,4])
even = a%2==0 #짝수값만 뽑고 싶다
even # 불린 마스크

array([False,  True, False,  True])

In [157]:
# 불린 마스크를 인덱스로 사용하면 True값 만 뽑힙니다
a[even]

array([2, 4])

In [168]:
import numpy as np

In [169]:
a = np.array([1,2,3])

In [172]:
a, a.dtype, a.shape

(array([1, 2, 3]), dtype('int32'), (3,))

In [180]:
np.zeros(shape=(2, 3, 4), dtype=np.int32)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [182]:
np.ones(shape=(3, 2, 4), dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [190]:
np.ones(shape=(random.randint(1,4), random.randint(1,4), random.randint(1,4)), dtype=np.int32)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [193]:
np.full((3, 2, 4), 3.14)

array([[[3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14]]])

In [197]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [199]:
#사용 빈도 순위 zeros, ones, arange
np.arange(0,10,3)

array([0, 3, 6, 9])

In [203]:
np.linspace(1,10, 5) #시작값, 끝값, x 등분

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [205]:
# width 100 M , 건물 3채
np.linspace(0,100, 3+1)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [206]:
np.linspace(150, 200, 5)

array([150. , 162.5, 175. , 187.5, 200. ])

In [208]:
import random
random.randint(1,10)

2

In [211]:
np.random.rand(2,3) #[0,1]

array([[0.92210715, 0.09806602, 0.96530752],
       [0.96335602, 0.0914816 , 0.42008188]])

In [212]:
np.random.normal(size=(2,3)) #종모양의 정규 분포 , 평균값이 많이 뽑힙니다

array([[ 0.23961185,  0.89636333, -0.57887443],
       [-1.40875898, -0.39556324,  1.0969155 ]])

In [213]:
np.random.randint(low=1, high=10, size=(2,3))

array([[8, 8, 5],
       [3, 9, 5]])

In [215]:
np.random.uniform(size=(2,3)) #전체값에서 균등하게 뽑힙니다, 제어 가능

array([[0.52878534, 0.47615899, 0.05277559],
       [0.05361357, 0.81348862, 0.57607525]])

In [227]:
a = np.ones(shape=(3,2), dtype=np.int)
b = np.ones(shape=(3,2), dtype=np.float)  # broadcasting 
a + b 

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [229]:
# 행우선으로 저장됩니다
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [230]:
b = a.reshape((2,3))
b
'''
Fortran, R 은 기본 방향이 열방향
[[0,3]
 [1,4]
 [2,5]]
'''

array([[0, 1, 2],
       [3, 4, 5]])

In [237]:
#차원 갯수, *모양* , 총 요소 갯수, 데이터 타입, 메모리 사용량
b.ndim, b.shape, b.size , b.dtype, b.nbytes

(2, (2, 3), 6, dtype('int32'), 24)

In [239]:
b.flatten() # 1차원으로 변환 flatten:평면화

array([0, 1, 2, 3, 4, 5])

In [372]:
#slicing : 데이터를 자르기
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

a에서 다음 원소들을 잘라주세요  [ 시작:끝, 시작:끝] 
- [1,4,7]
- [6,7,8]
- [1,2,4,5,7,8]
- [4,5,7,8]

In [373]:
a[:, 1], a[-1], a[:,1:].flatten(), a[1:,1:].flatten()

(array([1, 4, 7]),
 array([6, 7, 8]),
 array([1, 2, 4, 5, 7, 8]),
 array([4, 5, 7, 8]))

In [374]:
#slicing : 데이터를 자르기
b = np.arange(12).reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

b에서 아래 요소/원소(element) 를 잘라(slice) 주세요
- [5,6,9,10]
- [9,10,11]

In [375]:
b[1:,1:-1].flatten(), b[-1, 1:]  

(array([ 5,  6,  9, 10]), array([ 9, 10, 11]))

In [376]:
# 3차원 
c = np.arange(2*3*4).reshape((2,3,4))
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [377]:
#[6, 10],  [17, 18, 19],  [13,14,17,18] 를 잘라주세요, 2시에 수업 시작
c[0, 1:, 2], c[1,1,1:], c[1, :2, 1:3].flatten()

(array([ 6, 10]), array([17, 18, 19]), array([13, 14, 17, 18]))

In [378]:
#[ 0,  1,  2,  3], [12, 13, 14, 15], [1, 5, 9], [15, 19, 23]
c[0, 0, :], c[1, 0], c[0, :, 1],  c[1, :, -1]

(array([0, 1, 2, 3]),
 array([12, 13, 14, 15]),
 array([1, 5, 9]),
 array([15, 19, 23]))

In [379]:
c.shape
c.reshape((6,4)), np.reshape(c, (3,8)) #편한대로 사용

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]))

In [380]:
c.size, c.reshape((-1, 4)) #-1(unknown dimension) 알아서 맞춰라 1번만 사용

(24, array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [381]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a, b

(array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [382]:
# 두 배열을 붙입니다 concatenate == concat
c = np.concatenate((a,b,a), axis=0) 
a.shape, c.shape, c

((2, 3), (6, 3), array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [ 0,  1,  2],
        [ 3,  4,  5]]))

In [383]:
c = np.concatenate((a,b,a), axis=1) 
c

array([[ 0,  1,  2,  6,  7,  8,  0,  1,  2],
       [ 3,  4,  5,  9, 10, 11,  3,  4,  5]])

data0 = data1.csv
data1 = data2.csv 
data = np.concatenate((data0, data1), axis=0)

In [384]:
c = np.stack((a,b,a,b), axis=2) # axis를 지정한 곳에 배열들이 쌓입니다
# axis=0  (4,2,3)
# axis=1  (2,4,3)
# axis=2  (2,3,4)

In [385]:
# stack 쌓다 , 쌓으면 차원이 1 증가합니다
a.shape, b.shape, c.shape

((2, 3), (2, 3), (2, 3, 4))

In [386]:
#stack 활용 예
#[첫번째 학생, 두번째 학생, 세번째 학생]    
kor = [80, 90, 99]
eng = [70, 50, 60]
score = np.stack((kor, eng), axis=1)
score

array([[80, 70],
       [90, 50],
       [99, 60]])

In [387]:
score

array([[80, 70],
       [90, 50],
       [99, 60]])

In [388]:
math = np.array([20, 30, 40])
math

array([20, 30, 40])

In [389]:
score.shape, math.shape

((3, 2), (3,))

In [390]:
#3차원이 되면 안됩니다. stack 사용하면 차원이 늘어나요
math = np.array([20, 30, 40]).reshape((3,1))
score = np.concatenate((score, math), axis=-1)# -1 은 마지막 차원을 가리킵니다
score

array([[80, 70, 20],
       [90, 50, 30],
       [99, 60, 40]])

In [391]:
# 4번째 학생의 국영수 점수가 추가됐습니다
# 모든 데이터를 하나로 통합하세요
score_4 = np.array([100,90,90]).reshape((1, 3))
score = np.concatenate((score, score_4), axis=0)
score

array([[ 80,  70,  20],
       [ 90,  50,  30],
       [ 99,  60,  40],
       [100,  90,  90]])

In [392]:
score.shape

(4, 3)

In [393]:
#각 과목별 평균은? 
np.mean(score, axis=0) 

array([92.25, 67.5 , 45.  ])

In [394]:
#시험을 가장 잘 본 학생의 평균 점수는?
#3과목 평균중 가장 높은 점수는? 
np.max(np.mean(score, axis=1))

93.33333333333333

In [395]:
score

array([[ 80,  70,  20],
       [ 90,  50,  30],
       [ 99,  60,  40],
       [100,  90,  90]])

In [396]:
# save
#np.save()#binary file in NumPy ``.npy
#(%10.5f)  '%.2f':소수점 2번째 자리까지 %d 정수만
np.savetxt('score_sample.txt', score, '%d') #text file.

In [397]:
# read , open, load 키워드로 찾아봅니다
s = np.loadtxt('score_sample.txt')
s

array([[ 80.,  70.,  20.],
       [ 90.,  50.,  30.],
       [ 99.,  60.,  40.],
       [100.,  90.,  90.]])

In [400]:
s[:,::-1] # 시작부터 끝까지 거꾸로

array([[ 20.,  70.,  80.],
       [ 30.,  50.,  90.],
       [ 40.,  60.,  99.],
       [ 90.,  90., 100.]])

In [401]:
s[:, ::2] #시작부터 끝까지 스텝(간격) 2

array([[ 80.,  20.],
       [ 90.,  30.],
       [ 99.,  40.],
       [100.,  90.]])

In [402]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [407]:
#시작부터 끝까지 2칸씩 뛰면서 = 짝수
#1번째 요소부터 끝까지 2칸씩 뛰면서 = 홀수
#2번째 요소부터 6번째 요소까지 2칸씩 뛰면서
#[시작:끝:간격] 생략하면 기본값 시작=0, 끝:끝, 간격:1
a[::2], a[1::2], a[2:6:2]

(array([0, 2, 4, 6, 8]), array([1, 3, 5, 7, 9]), array([2, 4]))

In [409]:
#분리하기 index의 복수가 indices
np.split(a, [1,7]) # 해당 위치를 잘라라

[array([0]), array([1, 2, 3, 4, 5, 6]), array([7, 8, 9])]

In [414]:
#분리하기 section 갯수
#머신러닝에서 데이터 셋을 k 개 분리해서 k-fold validation set 을 만듭니다
#k = 3 이라면, 데이터를 3개로 분리해서 2개 셋은 학습, 1개 셋은 테스트로 사용
'''
3-fold validation set
ABC
학습 : AB   테스트 : C
학습 : BC   테스트 : A
학습 : AC   테스트 : B
'''
np.split(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

##### 브로드 캐스팅

배열의 모양이 서로 다를 때 연산이 가능하게 해주는 기능

In [418]:
a * 2 #브로드 캐스팅이 적용 되어서 연산 가능

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [419]:
a = np.array([0, 10, 20, 30])
a = np.stack((a,a,a), 1)
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [420]:
#배열 복제 np.repeat, np.tile
b = np.array([0,1,2])
b

array([0, 1, 2])

In [422]:
a.shape, b.shape

((4, 3), (3,))

In [421]:
a + b #브로드 캐스팅

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [429]:
a = np.arange(4)*10
a = a.reshape([-1, 1])
b = np.arange(3)
a.shape, b.shape

((4, 1), (3,))

In [434]:
a + b #브로드캐스팅

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

비교  > < == >=

In [436]:
7 == 3

False

In [445]:
a = np.arange(8)
b = np.arange(1,3)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [455]:
not True , not False

(False, True)

In [453]:
mask = a > 2
mask

array([False, False, False,  True,  True,  True,  True,  True])

In [451]:
# True 인 값만 선택됩니다 , boolean mask 를 이용한 indexing
a[mask]

array([3, 4, 5, 6, 7])

In [456]:
np.logical_not(mask)

array([ True,  True,  True, False, False, False, False, False])

In [457]:
np.logical_and(mask, mask)

array([False, False, False,  True,  True,  True,  True,  True])

In [458]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [460]:
# 짝수이면서 2보다 큰 값을 뽑으세요 logical_and , [mask] 를 이용해서
mask0 = a % 2 == 0
mask1 = a > 2
mask0, mask1

(array([ True, False,  True, False,  True, False,  True, False]),
 array([False, False, False,  True,  True,  True,  True,  True]))

In [461]:
mask = np.logical_and(mask0, mask1)
mask

array([False, False, False, False,  True, False,  True, False])

In [462]:
a[mask]

array([4, 6])

In [463]:
#정렬
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [465]:
np.sort(a)[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

주식 데이터 2개를 받아서 concatenate 로 붙이세요
df = pandas.read_csv() 로 파일 읽고
arr0 = np.array(df[ ]) 필요한 숫자 부분만
arr = np.concatenate((arr0, arr1), axis=0)